server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 192.168.247.130
    port: 6379
    password: 'dmlab@neu'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  # RabbitMQ配置
  rabbitmq:
    host: 192.168.247.130
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: correlated  # 确认消息已发送到交换机（交互类型）
    publisher-returns: true
    template:
      mandatory: true #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    # 消费者配置
    listener:
      direct:
        auto-startup: true
        retry:
          enabled: true
          max-attempts: 3
      simple:
        acknowledge-mode: manual  # 设置消费者为手动确认模式
mybatis-plus:
  type-aliases-package: com.xydp.entity # 别名扫描包
logging:
  level:
    com.ddpw: debug